# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schemas

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HydrationMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HydrationMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHydrationMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HydrationMessageBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x42\x4B\x48\x4D", size_prefixed=size_prefixed)

    # HydrationMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HydrationMessage
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HydrationMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    HydrationMessageStart(builder)

def HydrationMessageAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    HydrationMessageAddName(builder, name)

def HydrationMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return HydrationMessageEnd(builder)
