# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schemas

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserSignup(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserSignup()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserSignup(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserSignup
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserSignup
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserSignup
    def Password(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UserSignupStart(builder):
    builder.StartObject(2)

def Start(builder):
    UserSignupStart(builder)

def UserSignupAddUsername(builder, username):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)

def AddUsername(builder, username):
    UserSignupAddUsername(builder, username)

def UserSignupAddPassword(builder, password):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(password), 0)

def AddPassword(builder, password):
    UserSignupAddPassword(builder, password)

def UserSignupEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserSignupEnd(builder)
