# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schemas

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserAuth(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserAuth()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserAuth(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserAuth
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserAuth
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserAuth
    def Password(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UserAuthStart(builder):
    builder.StartObject(2)

def Start(builder):
    UserAuthStart(builder)

def UserAuthAddUsername(builder, username):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)

def AddUsername(builder, username):
    UserAuthAddUsername(builder, username)

def UserAuthAddPassword(builder, password):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(password), 0)

def AddPassword(builder, password):
    UserAuthAddPassword(builder, password)

def UserAuthEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserAuthEnd(builder)
